### ISSUE TITLE
Possibility for Nanopore data

### ISSUE THREAD

**Issue by josiegleeson** [Magdoll/SQANTI2#29]
Hi,

This pipeline looks great, and I am wanting to try and run it for my data which is from direct RNA with Nanopore. Do you think this is possible? I tried running it with a fasta file but got an error about the read ID.

Thank you for your help.

**Comment by Magdoll** [comment]
Hi @josiegleeson ,

SQANTI2 is designed with high quality (>99% accuracy) full-length reads in mind. I cannot guarantee performance on other platforms. Right now it also assumes it must have a particular ID format (due to common ID parsing issues that can come downstream from it).

The expected ID format is `PB.X.Y` where X and Y are both integers. You can modify your data input to work with the ID.

Thanks,
--Liz
