### ISSUE TITLE
Result analysis

### ISSUE THREAD

**Issue by ljw90607** [Magdoll/SQANTI2#3]
Dear @Magdoll,

Thank you for providing a wonderful tool for long read data analysis.
I am actually trying running SQANTI2 using cDNA nanopore data and I wanted to ask you some about the result.

1. When I look at the characterization of transcripts which gives me how many isoforms are falling into each category (FSM, ISM, NIC etc..), I found that about half of isoforms detected as unique isoforms are falling into antisense category. These isoforms are also labeled as novel isoforms. Although I need to check if these reads are the opposite stranded reads or not, but I am wondering whether SQANTI2 can annotate these antisense reads into opposite stranded reads.

Jungwoo

**Comment by Magdoll** [comment]
Hi @ljw90607 ,

If most of your data is counted as anti-sense, most likely it's because the data is not stranded.

SQANTI2 trusts the input sequence as the sense strand. By default minimap2 is called with `-uf` parameter. If your input data is not stranded, you will either need to manually modify the minimap2 parameter in `sqanti_qc2.py` or modify the input sequences so they are stranded.

--Liz

**Comment by ljw90607** [comment]
Dear @Magdoll, 

We have tried to use the sqanti_qc2.py without the option -uf which then would be mapping the transcripts as unknown. But we found out that even without the -uf parameter, I was still getting the half of my reads as antisense. 
Would there be any suggestion on how I can annotate these antisense strands correctly? 
Thank you for your help.

**Comment by Magdoll** [comment]
Hi @ljw90607 ,
Since I'm not familiar with nanopore data, I will not be able to help much further. I can only offer the experience for PacBio Iso-Seq data.

Thanks,
-Liz
