### ISSUE TITLE
Error with sqanti_qc2.py command

### ISSUE THREAD

**Issue by tfiskur** [Magdoll/SQANTI2#66]
Hello!

I have tried to run the sqanti_qc2.py command with the "all_samples.chained.gtf", annotation and genome fasta files. The program stopped with the next error in the end:

`FileNotFoundError: [Errno 2] No such file or directory: '/home/smrtanalysis/Downloads/SQANTI2-master/killifish/chain_truncated_isoforms_as_different_filtered/splits/0/all_samples.chained_corrected.faa`

That is strange because the corrected.faa file should be the output of the SQANTI2. Why does the program require its presence?

Also, in the terminal I see this error prior to the final one:

`Traceback (most recent call last):
  File "/home/smrtanalysis/anaconda3/envs/anaCogen/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/smrtanalysis/anaconda3/envs/anaCogen/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "sqanti_qc2.py", line 1654, in run
    orfDict = correctionPlusORFpred(args, genome_dict)
  File "sqanti_qc2.py", line 591, in correctionPlusORFpred
    if subprocess.check_call(cmd, shell=True, cwd=gmst_dir)!=0:
  File "/home/smrtanalysis/anaconda3/envs/anaCogen/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'perl /home/smrtanalysis/Downloads/SQANTI2-master/killifish/chain_truncated_isoforms_as_different_filtered/utilities/gmst/gmst.pl -faa --strand direct --fnn --output /home/smrtanalysis/Downloads/SQANTI2-master/killifish/chain_truncated_isoforms_as_different_filtered/splits/2/GMST/GMST_tmp /home/smrtanalysis/Downloads/SQANTI2-master/killifish/chain_truncated_isoforms_as_different_filtered/splits/2/all_samples.chained_corrected.fasta' returned non-zero exit status 2.
Skipping aligning of sequences because GTF file was provided.`

Would be grateful for any help.

**Comment by Magdoll** [comment]
Hi @tfiskur ,

The error message and the lack of an output `.faa` means GMST (ORF prediction) failed.

You can try to troubleshoot GMST by running the failed command:
```
perl /home/smrtanalysis/Downloads/SQANTI2-master/killifish/chain_truncated_isoforms_as_different_filtered/utilities/gmst/gmst.pl -faa --strand direct --fnn --output /home/smrtanalysis/Downloads/SQANTI2-master/killifish/chain_truncated_isoforms_as_different_filtered/splits/2/GMST/GMST_tmp /home/smrtanalysis/Downloads/SQANTI2-master/killifish/chain_truncated_isoforms_as_different_filtered/splits/2/all_samples.chained_corrected.fasta
```

If ORF prediction is not necessary you can turn it off with `--skipORF`

--Liz

**Comment by tfiskur** [comment]
Dear Liz, thanks a lot. I will try.

Upd. Thanks! It worked.

**Comment by tfiskur** [comment]
I tried the command that you proposed. It run, but the .classification file remained empty. If I try to rerun the sqanti_qc2.py command after that, it outputs an error: 
`WARNING: splits/ directory already exists! Abort!`

I would really like to have the ORF prediction, but also tried the --skipORF variant:
`python3.7 sqanti_qc2.py -t 30 -n 10 --gtf --skipORF all_samples.chained.gtf annotation2015.gtf softmasked_genome.fa --fl_count all_samples.chained_count.txt`

It output the same error 
`FileNotFoundError: [Errno 2] No such file or directory: '/home/smrtanalysis/Downloads/SQANTI2-master/killifish/chain_truncated_isoforms_as_different_filtered/splits/0/all_samples.chained_classification.txt'` 
and also: 
`FL count file all_samples.chained_count.txt does not exist!`

If I can provide any further information please let me know.

**Comment by anilkanthi** [comment]
Hi,

I am having the following gmst.pl error: 

python sqanti_qc2.py -t 30 --gtf bc1001.gtf  gencode.v33.annotation.gtf /gpfs/data/skoklab/home/shared-ali-anil/ref_data/ref/hg38/hg38.fa --fl_count tofu.collapsed.abundance.txt 
R scripting front-end version 3.6.1 (2019-07-05)
Write arguments to /gpfs/data/skoklab/home/kantha01/iso_seq/softwares/SQANTI2/bc1001.params.txt...
**** Running SQANTI2...
**** Parsing provided files....
Reading genome fasta /gpfs/data/skoklab/home/shared-ali-anil/ref_data/ref/hg38/hg38.fa....
Skipping aligning of sequences because GTF file was provided.

Indels will be not calculated since you ran SQANTI2 without alignment step (SQANTI2 with gtf format as transcriptome input).
**** Predicting ORF sequences...
GeneMarkS: error on last system call, error code 7
Abort program!!!
Traceback (most recent call last):
  File "sqanti_qc2.py", line 2198, in <module>
    main()
  File "sqanti_qc2.py", line 2191, in main
    run(args)
  File "sqanti_qc2.py", line 1654, in run
    orfDict = correctionPlusORFpred(args, genome_dict)
  File "sqanti_qc2.py", line 591, in correctionPlusORFpred
    if subprocess.check_call(cmd, shell=True, cwd=gmst_dir)!=0:
  File "/gpfs/home/kantha01/.conda/envs/anaCogent3/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '**perl /gpfs/data/skoklab/home/kantha01/iso_seq/softwares/SQANTI2/utilities/gmst/gmst.pl** -faa --strand direct --fnn --output /gpfs/data/skoklab/home/kantha01/iso_seq/softwares/SQANTI2/GMST/GMST_tmp /gpfs/data/skoklab/home/kantha01/iso_seq/softwares/SQANTI2/bc1001_corrected.fasta' returned non-zero exit status 1.

After which I ran the failed command and it worked!:
**perl /gpfs/data/skoklab/home/kantha01/iso_seq/softwares/SQANTI2/utilities/gmst/gmst.pl -faa --strand direct --fnn --output /gpfs/data/skoklab/home/kantha01/iso_seq/softwares/SQANTI2/GMST/GMST_tmp /gpfs/data/skoklab/home/kantha01/iso_seq/softwares/SQANTI2/bc1001_corrected.fasta**

But the main command gives the same error. I do require the ORF analysis.
How do I go ahead with this?

**Comment by anilkanthi** [comment]
When I run it with --skipORF, I get a Rscript error:

python sqanti_qc2.py -t 30 --gtf bc1001.gtf  gencode.v33.annotation.gtf /gpfs/data/skoklab/home/shared-ali-anil/ref_data/ref/hg38/hg38.fa --fl_count tofu.collapsed.abundance.txt --skipORF
R scripting front-end version 3.6.1 (2019-07-05)
Write arguments to /gpfs/data/skoklab/home/kantha01/iso_seq/softwares/SQANTI2/bc1001.params.txt...
**** Running SQANTI2...
**** Parsing provided files....
Reading genome fasta /gpfs/data/skoklab/home/shared-ali-anil/ref_data/ref/hg38/hg38.fa....
Error corrected FASTA /gpfs/data/skoklab/home/kantha01/iso_seq/softwares/SQANTI2/bc1001_corrected.fasta already exists. Using it...
**** Predicting ORF sequences...
WARNING: Skipping ORF prediction because user requested it. All isoforms will be non-coding!
WARNING: All input isoforms were predicted as non-coding
**** Parsing Reference Transcriptome....
**** Parsing Isoforms....
Splice Junction Coverage files not provided.
**** Performing Classification of Isoforms....
Number of classified isoforms: 24533
**** RT-switching computation....
**** Reading Full-length read abundance files...
Single-sample PacBio FL count format detected.
Isoforms expression files not provided.
**** Writing output files....
**** Generating SQANTI2 report....
Traceback (most recent call last):
  File "sqanti_qc2.py", line 2198, in <module>
    main()
  File "sqanti_qc2.py", line 2191, in main
    run(args)
  File "sqanti_qc2.py", line 1844, in run
    if subprocess.check_call(cmd, shell=True)!=0:
  File "/gpfs/home/kantha01/.conda/envs/anaCogent3/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '**/gpfs/share/apps/R/3.6.1/bin/Rscript** /gpfs/data/skoklab/home/kantha01/iso_seq/softwares/SQANTI2/utilities//SQANTI_report2.R /gpfs/data/skoklab/home/kantha01/iso_seq/softwares/SQANTI2/bc1001_classification.txt /gpfs/data/skoklab/home/kantha01/iso_seq/softwares/SQANTI2/bc1001_junctions.txt /gpfs/data/skoklab/home/kantha01/iso_seq/softwares/SQANTI2/bc1001.params.txt' died with <Signals.SIGKILL: 9>.
